#step 1: import pandas lib

In [60]:
import pandas as pd

In [42]:
data ={'Name':['prana','ram','abhishek','siri'],
       'Age':[23,34,45,56],
       'city':['hyderabad','mumbai','delhi','bangalore'] }
data

{'Name': ['prana', 'ram', 'abhishek', 'siri'],
 'Age': [23, 34, 45, 56],
 'city': ['hyderabad', 'mumbai', 'delhi', 'bangalore']}

#method 1 : DataFrame

In [46]:
#convert dictionary to dataframe
df=pd.DataFrame(data) #table name
df

       Name  Age       city
0     prana   23  hyderabad
1       ram   34     mumbai
2  abhishek   45      delhi
3      siri   56  bangalore

In [27]:
#create s 4 dim array
array_4d = [[[[1,2],[3,4]],[[5,6],[7,8]]],
             [[[9,10],[11,12]],[[13,14],
               [15,16]]]]
array_4d

[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
 [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]

In [28]:
df=pd.DataFrame(array_4d) #table name
df

                     0                     1
0     [[1, 2], [3, 4]]      [[5, 6], [7, 8]]
1  [[9, 10], [11, 12]]  [[13, 14], [15, 16]]

In [29]:
df_array = pd.DataFrame(array_4d,columns=(['col1','col2']))
#if array ther will be no column name so
df_array

                  col1                  col2
0     [[1, 2], [3, 4]]      [[5, 6], [7, 8]]
1  [[9, 10], [11, 12]]  [[13, 14], [15, 16]]

Method 2: Rename

In [ ]:
df.rename(columns={'Name':'Full Name','Age':'Age in years','city':'Location'},inplace=True)
df
#we use inplace to make changes in the same dataframe otherwise it will create a new dataframe with changes

  Full Name  Age in years   Location
0     prana            23  hyderabad
1       ram            34     mumbai
2  abhishek            45      delhi
3      siri            56  bangalore

In [52]:
df

  Full Name  Age in years   Location
0     prana            23  hyderabad
1       ram            34     mumbai
2  abhishek            45      delhi
3      siri            56  bangalore

#Step 3 : load the datasets from sys

In [96]:

import pandas as pd

df = pd.read_csv(r"C:\Users\prana\OneDrive\Desktop\tekworks\dataset.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150.0,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187.0,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172.0,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178.0,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163.0,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123.0,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132.0,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141.0,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,NaN,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174.0,0,0.0,1,1,2,0

In [76]:
df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [77]:
df.tail(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [78]:
df.sample(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
172,58,1,1,120,284,0,0,160,0,1.8,1,0,2,0
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2,0
286,59,1,3,134,204,0,1,162,0,0.8,2,2,2,0
120,64,0,0,130,303,0,1,122,0,2.0,1,2,2,1
23,61,1,2,150,243,1,1,137,1,1.0,1,0,2,1
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2,1
153,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1
285,46,1,0,140,311,0,1,120,1,1.8,1,2,3,0
245,48,1,0,124,274,0,0,166,0,0.5,1,0,3,0
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [80]:
#method 6:describe()
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [85]:
#method7: finding nan values 
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [84]:
df.isna().sum() #same as before 2 techniques

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [86]:
#method8: value of count 
df['age'].value_counts()

age
58    19
57    17
54    16
59    14
52    13
51    12
62    11
44    11
56    11
60    11
64    10
41    10
63     9
67     9
65     8
53     8
61     8
45     8
43     8
42     8
55     8
66     7
48     7
50     7
46     7
49     5
47     5
68     4
39     4
35     4
70     4
40     3
69     3
38     3
71     3
37     2
34     2
29     1
74     1
76     1
77     1
Name: count, dtype: int64

In [87]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [88]:
df.shape

(303, 14)

In [102]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

handle missing values

In [104]:
#method 10: fillna
df['thalach'].fillna('0',inplace=True)

In [105]:
df.sort_values(by='age',ascending=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
72,29,1,1,130,204,0,0,202.0,0,0.0,2,0,2,1
58,34,1,3,118,182,0,0,174.0,0,0.0,2,0,2,1
125,34,0,1,118,210,0,1,192.0,0,0.7,2,0,2,1
65,35,0,0,138,183,0,1,182.0,0,1.4,2,0,2,1
227,35,1,0,120,198,0,1,130.0,1,1.6,1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,71,0,0,112,149,0,1,125.0,0,1.6,1,0,2,1
60,71,0,2,110,265,1,0,130.0,0,0.0,2,1,2,1
129,74,0,1,120,269,0,0,121.0,1,0.2,2,1,2,1
144,76,0,2,140,197,0,2,116.0,0,1.1,1,0,2,1
238,77,1,0,125,304,0,0,162.0,1,0.0,2,3,2,0

In [120]:
df.groupby('sex')[['age','chol']].mean()

           age        chol
sex
0    55.677083  261.302083
1    53.758454  239.289855

In [124]:
#iloc and loc methods
df.iloc[0:5,0:3]  #iloc is index based selection [rows,columns]

   age  sex  cp
0   63    1   3
1   37    1   2
2   41    0   1
3   56    1   1
4   57    0   0

In [126]:
df.loc[0:5,['age','sex']]  #loc is label based selection [rows,columns] positions
df.loc[0:5,df.columns[0:3]]

   age  sex  cp
0   63    1   3
1   37    1   2
2   41    0   1
3   56    1   1
4   57    0   0
5   57    1   0

In [127]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [128]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach      object
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [129]:
#astype method to change the data type of a column
df['oldpeak']=df['oldpeak'].astype('int32')

In [130]:
df['oldpeak'].dtype

dtype('int32')

In [132]:
#method 16: unique 
#all  columns unique valuesfor a column
for col in df.columns:
    print(f"{col}: {df[col].unique()} \n")

age: [63 37 41 56 57 44 52 54 48 49 64 58 50 66 43 69 59 42 61 40 71 51 65 53
 46 45 39 47 62 34 35 29 55 60 67 68 74 76 70 38 77]

sex: [1 0]

cp: [3 2 1 0]

trestbps: [145 130 120 140 172 150 110 135 160 105 125 142 155 104 138 128 108 134
 122 115 118 100 124  94 112 102 152 101 132 148 178 129 180 136 126 106
 156 170 146 117 200 165 174 192 144 123 154 114 164]

chol: [233 250 204 236 354 192 294 263 199 168 239 275 266 211 283 219 340 226
 247 234 243 302 212 175 417 197 198 177 273 213 304 232 269 360 308 245
 208 264 321 325 235 257 216 256 231 141 252 201 222 260 182 303 265 309
 186 203 183 220 209 258 227 261 221 205 240 318 298 564 277 214 248 255
 207 223 288 160 394 315 246 244 270 195 196 254 126 313 262 215 193 271
 268 267 210 295 306 178 242 180 228 149 278 253 342 157 286 229 284 224
 206 167 230 335 276 353 225 330 290 172 305 188 282 185 326 274 164 307
 249 341 407 217 174 281 289 322 299 300 293 184 409 259 200 327 237 218
 319 166 311 169 187 176 241 131]

fbs: [1 0]

restecg: [0 1 2]

thalach: [150.0 187.0 172.0 178.0 163.0 148.0 153.0 173.0 162.0 174.0 160.0 139.0
 171.0 144.0 158.0 114.0 'mean' 161.0 179.0 137.0 157.0 123.0 152.0 168.0
 140.0 188.0 170.0 151.0 142.0 180.0 143.0 182.0 156.0 115.0 149.0 146.0
 175.0 186.0 159.0 130.0 190.0 165.0 147.0 154.0 202.0 166.0 164.0 184.0
 122.0 169.0 138.0 111.0 145.0 194.0 131.0 133.0 155.0 167.0 192.0 121.0
 96.0 126.0 105.0 181.0 116.0 125.0 108.0 132.0 120.0 112.0 128.0 109.0
 113.0 99.0 177.0 141.0 136.0 97.0 127.0 103.0 124.0 88.0 195.0 106.0 95.0
 117.0 71.0 134.0 90.0]

exang: [0 1]

oldpeak: [2 3 1 0 4 6 5]

slope: [0 2 1]

ca: [0 2 1 3 4]

thal: [1 2 3 0]

target: [1 0]

In [137]:
#method 17: nunique- number of unique values in each column
df['cp'].nunique()

4

In [142]:
df[(df['age']>20) & (df['age']<60)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1,37,1,2,130,250,0,1,187.0,0,3,0,0,2,1
2,41,0,1,130,204,0,0,172.0,0,1,2,0,2,1
3,56,1,1,120,236,0,1,178.0,0,0,2,0,2,1
4,57,0,0,120,354,0,1,163.0,1,0,2,0,2,1
5,57,1,0,140,192,0,1,148.0,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,59,1,0,164,176,1,0,90.0,0,1,1,2,1,0
298,57,0,0,140,241,0,1,123.0,1,0,1,0,3,0
299,45,1,3,110,264,0,1,132.0,0,1,1,0,3,0
301,57,1,0,130,131,0,1,mean,1,1,1,1,3,0
302,57,0,1,130,236,0,0,174.0,0,0,1,1,2,0

In [144]:
df[(df['chol']>250)]
print("high cholesterol levels")
df[(df['chol']<30)]
print("low cholesterol levels")

high cholesterol levels
low cholesterol levels

In [147]:
df['chol_status']=df['chol'].apply(
    lambda x: 'high' if x>200 else ('low' if x<50 else 'normal')
)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,chol_status
0,63,1,3,145,233,1,0,150.0,0,2,0,0,1,1,high
1,37,1,2,130,250,0,1,187.0,0,3,0,0,2,1,high
2,41,0,1,130,204,0,0,172.0,0,1,2,0,2,1,high
3,56,1,1,120,236,0,1,178.0,0,0,2,0,2,1,high
4,57,0,0,120,354,0,1,163.0,1,0,2,0,2,1,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123.0,1,0,1,0,3,0,high
299,45,1,3,110,264,0,1,132.0,0,1,1,0,3,0,high
300,68,1,0,144,193,1,1,141.0,0,3,1,2,3,0,normal
301,57,1,0,130,131,0,1,mean,1,1,1,1,3,0,normal
302,57,0,1,130,236,0,0,174.0,0,0,1,1,2,0,high

In [149]:
safe_data = df.copy()
safe_data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,chol_status
0,63,1,3,145,233,1,0,150.0,0,2,0,0,1,1,high
1,37,1,2,130,250,0,1,187.0,0,3,0,0,2,1,high
2,41,0,1,130,204,0,0,172.0,0,1,2,0,2,1,high
3,56,1,1,120,236,0,1,178.0,0,0,2,0,2,1,high
4,57,0,0,120,354,0,1,163.0,1,0,2,0,2,1,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123.0,1,0,1,0,3,0,high
299,45,1,3,110,264,0,1,132.0,0,1,1,0,3,0,high
300,68,1,0,144,193,1,1,141.0,0,3,1,2,3,0,normal
301,57,1,0,130,131,0,1,mean,1,1,1,1,3,0,normal
302,57,0,1,130,236,0,0,174.0,0,0,1,1,2,0,high

In [ ]:
#saved datasets
df.to_csv('safe_dataset.csv',index=False)

In [151]:
#check duplicates
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Length: 303, dtype: bool

In [152]:
#drop duplicates
df.drop_duplicates(inplace=True)

In [153]:
df[df.duplicated()]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target, chol_status]
Index: []

In [154]:
df
df.reset_index('drop=True',inplace=True)
df

KeyError: 'Requested level (drop=True) does not match index name (None)'

In [155]:
#reset
#set_index
#replace
df["sex"].replace({0:'female',1:'male'},inplace=True)
df

C:\Users\prana\AppData\Local\Temp\ipykernel_19900\3199959509.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["sex"].replace({0:'female',1:'male'},inplace=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,chol_status
0,63,male,3,145,233,1,0,150.0,0,2,0,0,1,1,high
1,37,male,2,130,250,0,1,187.0,0,3,0,0,2,1,high
2,41,female,1,130,204,0,0,172.0,0,1,2,0,2,1,high
3,56,male,1,120,236,0,1,178.0,0,0,2,0,2,1,high
4,57,female,0,120,354,0,1,163.0,1,0,2,0,2,1,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,female,0,140,241,0,1,123.0,1,0,1,0,3,0,high
299,45,male,3,110,264,0,1,132.0,0,1,1,0,3,0,high
300,68,male,0,144,193,1,1,141.0,0,3,1,2,3,0,normal
301,57,male,0,130,131,0,1,mean,1,1,1,1,3,0,normal
302,57,female,1,130,236,0,0,174.0,0,0,1,1,2,0,high

In [156]:
df_final=pd.concat([safe_data,df],axis=0)
df_final

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,chol_status
0,63,1,3,145,233,1,0,150.0,0,2,0,0,1,1,high
1,37,1,2,130,250,0,1,187.0,0,3,0,0,2,1,high
2,41,0,1,130,204,0,0,172.0,0,1,2,0,2,1,high
3,56,1,1,120,236,0,1,178.0,0,0,2,0,2,1,high
4,57,0,0,120,354,0,1,163.0,1,0,2,0,2,1,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,female,0,140,241,0,1,123.0,1,0,1,0,3,0,high
299,45,male,3,110,264,0,1,132.0,0,1,1,0,3,0,high
300,68,male,0,144,193,1,1,141.0,0,3,1,2,3,0,normal
301,57,male,0,130,131,0,1,mean,1,1,1,1,3,0,normal
302,57,female,1,130,236,0,0,174.0,0,0,1,1,2,0,high